### ISSUE TITLE
Write the Python Azure Storage Blob Upload Script for Joshua to run

### ISSUE THREAD

**Issue by joshkyh** [SpectData/MONAH_Earnings_Call#5]
The folders structure is identical to 'tiny'

Let's upload all files in each company foler, including 1x features.csv and text.txt and all the mp3s.

Where to get the dictionary values
![image](https://user-images.githubusercontent.com/14764966/124748847-f1200d80-df66-11eb-9687-76388de8a6d6.png)

Credentials to Azure Storage Blob

https://github.com/joshkyh/iemocap/blob/master/Python2/laughter_detection/credentials.py

Use this download scripts as a guide, I'm sure we have a upload script.

https://github.com/joshkyh/iemocap/blob/master/Python2/laughter_detection/download_wav.py

Once commit and push, and tell me which file run, I'll run it for 3 days.

**Comment by mfmakahiya** [comment]
Hi Joshua! The file is /Stage_1/Audio_files_manipulation/upload_to_azure.py

Kindly make sure your version of azure-blob-storage is 2.1.0 for the script to run smoothly. You only need to edit line 41 with your local path.

Also, please help me delete the files in azure. I realized I don't have permission to delete the file so I can't remove the files uploaded during my test run. Thanks!

Let me know in case you encounter any issues.

**Comment by joshkyh** [comment]
Beautiful. The script worked perfectly. I just needed the win_cpu.yml file and the secrets directory which I got for myself in the VM. :)
